name: issk
description: درع الانترنت للأطفال - تطبيق توعوي لسلامة الأطفال على الإنترنت
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  video_player: ^2.8.1
  chewie: ^1.7.4
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^9.1.1
  sqflite_common_ffi_web: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/fonts/
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
